import type { Metadata } from 'next'
import './globals.css'

import Navbar from '@/components/Navbar/Navbar'

export const metadata: Metadata = {
  title: 'Notion Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ja'>
      <body className=''>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
